[workspace]
members = ["crates/rpc", "crates/core"]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
description = "RPC node for the Kakarot zk EVM"
homepage = "https://github.com/sayajin-labs/kakarot-rpc"
repository = "https://github.com/sayajin-labs/kakarot-rpc"
readme = "./README.md"
license = "MIT"

[workspace.dependencies]
starknet = { git = "https://github.com/xJonathanLEI/starknet-rs", rev = "d8eb791" }
reth-rpc-api = { git = "https://github.com/paradigmxyz/reth.git", rev = "fb710e5" }
reth-rpc-types = { git = "https://github.com/paradigmxyz/reth.git", rev = "fb710e5" }
reth-rlp = { git = "https://github.com/paradigmxyz/reth.git", rev = "fb710e5"  }
reth-primitives = { git = "https://github.com/paradigmxyz/reth.git", rev = "fb710e5" }
